name: Ubuntu CI

on: [push]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@arm64_bionic
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and test
        id: ci
        uses: ignition-tooling/action-ignition-ci@focal
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
